---
- hosts: all
  vars_files:
    - vars/main.yml
  pre_tasks:
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/authorized_keys.yml
    - import_tasks: tasks/bashrc.yml
    - import_tasks: tasks/zfs-load-key-service.yml

    - name: Install python3-apt
      package:
        name: python3-apt
        state: present
      become: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Update cache for Debian-based distros
      apt:
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'
      changed_when: false
      become: true

    - name: Upgrade the system
      package:
        name: "*"
        state: latest
      become: true
      when: upgrade|default(false)

  roles:
    - role: ansible-role-packages

    - role: geerlingguy.docker
      vars:
        docker_packages_state: present

    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
      when: lookup('env', 'TAILSCALE_KEY') | length > 0

  tasks:
    - name: Upgrade the system
      package:
        name: "*"
        state: latest
      become: true
      when: upgrade|default(false)
