- name: Template systemd zfs-load-key service
  template:
    src: files/zfs-load-key.service
    dest: /etc/systemd/system/zfs-load-key.service

- name: Enable the zfs-load-key service
  ansible.builtin.systemd:
    name: zfs-load-key
    enabled: true
